### ISSUE TITLE
Run button doesn't working in Pyhton Mode

### ISSUE THREAD

**Issue by ghost** [jdf/Processing.py-Bugs#208] opened 2018-01-08 17:39 UTC
I am using processing 3.3.6 pyhton mode in Windows 10 Pro X64. I am clicking to run button but doesn't work it. There isn't error message just don't working. In java mode, it works. 
![asd](https://user-images.githubusercontent.com/14164608/34683584-8261a616-f4b3-11e7-8876-e356cd13b30d.png)
I looked to mode folder. There is java folder but there isn't pyhton folder. I tried to uninstall pyhton mode and install again but doesn't work it.

**Comment by jdf** [comment] 2018-01-08 18:47
1) Does your Windows user name have non-ASCII characters in it? If so, this is a known bug in Python Mode, than I haven't been able to track down. The workaround is to create a new user with only ASCII characters in the name.

2) This may also be a sign of a networking firewall.

**Comment by hackingmath** [comment] 2018-03-24 15:27
I was having the same problem and once I unplugged the Ethernet or disconnected the wifi it worked.

**Comment by jdf** [comment] 2018-07-01 20:08
Duplicate of #202

**Closed as completed by jdf** 2018-07-01 20:08 UTC
Labels: duplicate
