### ISSUE TITLE
Gobal variables are unknown in Python function (Processing 3.0.2)

### ISSUE THREAD

**Issue by klrohe** [jdf/Processing.py-Bugs#150] opened 2016-02-28 16:19 UTC
The following Processing Python example

c = color(0)
x = 0.0
y = 100.0
speed = 1.0

def setup():
    size(200, 200)

def draw():
    background(255)
    move()
    display()

def move():
    x = x + speed
    if x > width:
        x = 0

def display():
    fill(c)
    rect(x, y, 30, 10)

results in the following error message:

processing.app.SketchException: UnboundLocalError: local variable 'x' referenced before assignment
	at jycessing.mode.run.SketchRunner.convertPythonSketchError(SketchRunner.java:247)
	at jycessing.mode.run.SketchRunner.access$4(SketchRunner.java:226)
	at jycessing.mode.run.SketchRunner$3.run(SketchRunner.java:121)
	at java.lang.Thread.run(Thread.java:745)

As my opinion is concerned this is a bug.

Kind Regards

Klaus

**Comment by Prabhnith** [comment] 2016-02-28 16:28
your code is not indent properly

**Comment by Prabhnith** [comment] 2016-02-28 16:33
add global x in move() and it will work properly.
It is not a bug. you can close it after checking this.

> `c = color(0)
> x = 0.0
> y = 100.0
> speed = 1.0
> 
> def setup():
>     size(200, 200)
> 
> 
> def draw():
>     background(255)
>     move()
>     display()
> 
> def move():
>     global x
>     x = x + speed
>     if x > width:
>         x = 0
> 
> def display():
>     fill(c)
>     rect(x, y, 30, 10)
> `

**Comment by klrohe** [comment] 2016-02-28 16:39
Hi Prabhnith ,

thanks for the hint it works now. The example I copied from 
http://py.processing.org/tutorials/objects/
It should be corrected.

Kind Regards

Klaus

the identation got lost when a pasted the code

**Comment by Prabhnith** [comment] 2016-02-28 17:46
actually the site is not updated since last year but the `global x` is included in the repository.
thanks for pointing out. Please close the issue.

**Closed** 2016-02-28 18:39 UTC
