### ISSUE TITLE
PVectors losing magnitude

### ISSUE THREAD

**Issue by pyNuts** [jdf/Processing.py-Bugs#174] opened 2016-10-31 00:26 UTC
For some reason using a PVector to make a ball bounce up and down always loses height over time and messes up after a few bounces, im not sure if its a fault with the python mode because its a pretty simple code.

Heres a simple example of what i mean, im new to classes but im pretty sure its not the code.

class Bounce:
    global location, velocity, acceleration

```
location = PVector(300,300)
velocity = PVector(0,0)
acceleration = PVector(0,1)

def update(self):
    velocity.add(acceleration)
    location.add(velocity)

def display(self):
    fill(0)
    ellipse(location.x, location.y, 20, 20)

def edge(self):
    if location.x <= 0 or location.x >= width-20:
        velocity.x *= -1
    if location.y <= 0 or location.y >= height-20:
        velocity.y *= -1
```

def setup():
    global b
    size(600,600)
    b = Bounce()

def draw():
    background(255)
    b.update()
    b.edge()
    b.display()

**Comment by pyNuts** [comment] 2016-10-31 10:22
I think I've found a solution.

If I add both forces in the update function to a For Loop, with a range of the number of forces, its will run through both before applying them, so far it seems to be working and not loosing any velocity.

Still, can anyone explain why it needed that in the first place?

**Comment by pyNuts** [comment] 2016-10-31 10:49
Well it worked for one example but now doesn't must be a bug.

**Comment by jdf** [comment] 2016-10-31 12:59
There is an error in your algorithm. Is this homework, or just for fun?

**Comment by pyNuts** [comment] 2016-10-31 20:35
Hi, its just fun, im kind of new to classes but have tried many ways and the ball keeps bleeding energy with each bounce, Ive tried the whole thing when location.y goes below height to set it as height before reversing velocity hoping that would help but no luck, ant recommendations?

I did manage to fix the ball going off screen issue though with location.y = height but its the magnitude of the bounce that is losing energy, Ive read multiple sources but nothing has worked.

**Comment by jdf** [comment] 2016-11-01 13:56
I believe the issues you're having are not a bug in Python Mode for Processing, so I'm closing the bug. Give the Processing forums a try for help with the bounce algorithm.

**Closed by jdf** 2016-11-01 13:56 UTC
